name: pipeline of AWS Elastic Container Service
on:
  push:
    branches:
      - master
env:
  ECR_REPOSITORY: mynginxapp
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: action checkout
        uses: actions/checkout@v4
      
      - name: AWS credentials configure
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: AWS ECR login configuration
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
