name: pipeline of AWS Elastic Container Service
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: productions
    steps:
      - name: action checkout
        uses: actions/checkout@v4
      
      - name: AWS credentials configure
        user: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: AWS ECR login configuration
        uses: aws-actions/amazon-ecr-login@v2

